### ISSUE TITLE
Add code navigation support to extension

### ISSUE THREAD

**Issue by bartv** [inmanta/vscode-inmanta#1]
This extension only provides syntax highlighting. For complex models code navigation is a must.

**Comment by wouterdb** [comment]
https://microsoft.github.io/language-server-protocol/specification
https://github.com/palantir/python-language-server

**Comment by wouterdb** [comment]
general approach

1. extend compiler to keep character range for each token instead of only the line number
1. extend compiler to build up a table mapping character range to symbol
1. build basic language server with support for 'navigate to definition' for symbols that can be resolved purely lexical (constructor calls, plugin calls, implements, type references,...)

extension to wider range of symbols 
1. extend compiler with type inference engine
1. extend language server for general 'navigate to definition'

**Comment by wouterdb** [comment]
Implement basic language server with goto definition support and error reporting

**Comment by wouterdb** [comment]
Todo
1-Add readme
2-Add feature flag to disable language server
