### ISSUE TITLE
Update LS of vscode extension if newer version available

### ISSUE THREAD

**Issue by FloLey** [inmanta/vscode-inmanta#1058]
~- if a newer version of inmanals is available propose the user to install it with a pop-up~
~- add a step for this to the walkthrough.~

Discussed in planning meeting: instead of the above do the following:

- [x] tie the extension to a specific language server version, update the release process to reflect this
- [x] when the extension starts, make sure to update the language server to the tied version (similar to how the language server is installed for the very first time).
- [x] make sure development is still possible, e.g. skip update when inmantals is installed in editable mode

**Comment by sanderr** [comment]
Discussed in planning meeting: instead of the above do the following:

- [ ] tie the extension to a specific language server version, update the release process to reflect this
- [ ] when the extension starts, make sure to update the language server to the tied version (similar to how the language server is installed for the very first time).
- [ ] make sure development is still possible, e.g. skip update when inmantals is installed in editable mode
